### ISSUE TITLE
Improve page navigation

### ISSUE THREAD

**Issue by axelpale** [axelpale/openmoji-sprites#1]
Improve navigation somehow. Implement either a table of contents or an accordion like suggested by @carlingmack in [openmoji/issues/170](https://github.com/hfg-gmuend/openmoji/issues/170).

GitHub Pages places reasonable limitations on the page layout and functionality. If we want to go beyond what is possible with GitHub Markdown, the project should be hosted elsewhere.

Any ideas?

**Comment by carlinmack** [comment]
You have a typo when you tried to tag me! found this anyway :)

Solution: https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab

**Comment by axelpale** [comment]
@carlinmack Oh, sorry! Life's little accidents :)

Thanks for the link. I tried my best to implement it, see https://github.com/axelpale/openmoji-sprites/commit/0508e158f2b01b2af56026385f17294f14de8438 https://github.com/axelpale/openmoji-sprites/commit/cfd4d4642c915831d18d46ba6f1014daacb5974d https://github.com/axelpale/openmoji-sprites/commit/6a0f671c774b02f1cdb09b95d020d0f8a0acca4e https://github.com/axelpale/openmoji-sprites/commit/cf36609871785303298baf15e24b6febe64e0677

Although I could get the open/close sections to work, the contents were rendered raw no matter what I tried. Links were just plain brackets and urls and there was no bullet point styling. See a sample image below.

I tried the empty line tricks discussed in your link. No success. I tried to remove html tags, images, and heading markup. No success.

**Weirdly enough**, everything looks good in my Atom Markdown Preview and in GitHub's own markdown editor. However, when the page is rendered via GitHub Pages, the sections stop working. There [might be some options](https://github.community/t5/GitHub-Pages/Collapsible-markdown-inside-lt-details-gt-lt-summary-gt-lt/td-p/13786) on which markdown renderer to use... but I do not want to go to that direction. Too messy.

**I think we should stick to the table of contents approach.** It is simple and fool proof. The table of contents approach also allows devs to quickly browse through the available sprites without forcing them to open and close every section separately.

Nevertheless, this was good to try it out and it was also interesting to hear such a feature exists!

![2020-04-23 sample](https://user-images.githubusercontent.com/992081/80086155-f8294e80-8561-11ea-854d-efb8daa7bbc6.png)

**Comment by carlinmack** [comment]
unfortunate to hear but I think that a table of contents approach is fine :) and yes GitHub markdown has some peculiarities about it, some good some bad
